name: Build Android APK

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Speeds up future builds by caching dependencies

      - name: Install Dependencies
        run: npm install

      - name: Generate Android Native Code (Expo Prebuild)
        run: npx expo prebuild --platform android --no-install

      - name: Make Gradle Executable
        # This fixes the "Permission Denied" error common in GitHub Actions
        run: chmod +x android/gradlew

      - name: Build APK (Release)
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: NuvioMobile-AMOLED-Android
          path: android/app/build/outputs/apk/release/app-release.apk
